simulated_joints:
  - head_pan_joint
  - head_tilt_joint
  - torso_lift_joint
  - elbow_flex_joint
  - forearm_roll_joint
  - shoulder_pan_joint
  - shoulder_lift_joint
  - upperarm_roll_joint
  - wrist_flex_joint
  - wrist_roll_joint
  - r_gripper_finger_joint
  - l_gripper_finger_joint
  - bellows_joint
  - gripper_joint
start_config:
  torso_lift_joint: 0.3861
  head_pan_joint: 0.253891
  head_tilt_joint: 1.22637
  upperarm_roll_joint: -1.41333
  shoulder_pan_joint: -1.19881
  shoulder_lift_joint: 0.623459
  forearm_roll_joint: -1.1064
  elbow_flex_joint: -2.15547
  wrist_flex_joint: -1.50969
  wrist_roll_joint: 0
  r_gripper_finger_joint: 0.05
  l_gripper_finger_joint: 0.05
controlled_joints:
  - head_pan_joint
  - head_tilt_joint
  - torso_lift_joint
  - elbow_flex_joint
  - forearm_roll_joint
  - shoulder_pan_joint
  - shoulder_lift_joint
  - upperarm_roll_joint
  - wrist_flex_joint
  - wrist_roll_joint
  - gripper_joint
fake_controllers: package://fetch_giskard/robots/fetch_fake_controllers.yaml
robot_urdf: package://fetch_giskard/robots/fetch.urdf
projection_mode: false
sim_frequency: 60
watchdog_period: 0.1