fetch:
  joint_velocity_controller:
    type: "robot_controllers/VelocityController"
    joints:
      - torso_lift_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - upperarm_roll_joint
      - elbow_flex_joint
      - forearm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
      - head_pan_joint
      - head_tilt_joint
    autostart: true

base_controller:
  type: "robot_controllers/DiffDriveBaseController"
  max_velocity_x: 1.0
  max_acceleration_x: 0.75
  # hold position
  moving_threshold: -0.01
  rotating_threshold: -0.01
  # autostart to get odom
  autostart: true
  # use laser to only slowly collide with things
  laser_safety_dist: 1.0

gravity_compensation:
  type: "robot_controllers/GravityCompensation"
  autostart: true
  

robot_driver:
  default_controllers:
    - "fetch/joint_velocity_controller"
    - "base_controller"
    - "gravity_compensation"
